HTTPOptions Lookup Flag
lifion/aws-sdk-js pull request #1
Opened 2020-10-30 17:13 UTC by vrMars

This PR adds the ability to pass down a lookup flag that will be used for DNS caching. 
##### Checklist

- [x] `npm run test` passes
- [x] `.d.ts` file is updated
- [x] changelog is added, `npm run add-change`
- [x] run `bundle exec rake docs:api` and inspect `doc/latest/index.html` if documentation is changed

2020-10-30 18:15 UTC, eaviles commented
Mm… no changes needed in lib/http/node.js?

2020-11-03 16:05 UTC, eaviles requested changes

2020-11-03 16:05 UTC, eaviles commented on lib/http/node.js
> +      lookup: httpOptions.lookup || dns.lookup
Instead of passing `dns.lookup` yourself if `httpOptions.lookup` is undefined, don't set anything in that case instead (keep old behavior).

2020-11-03 20:56 UTC, vrMars commented on lib/http/node.js
> +      lookup: httpOptions.lookup || dns.lookup
Addressed

2020-11-05 20:41 UTC, jennyEckstein requested changes

2020-11-05 20:41 UTC, jennyEckstein commented on .changes/next-release/feature-http-options-c24412db.json
> +  "description": "Added a lookup option to HTTPOptions that lets you pick a custom lookup function."
I think this can be worded better, maybe something like:
"Added a lookup attribute to HTTPOptions which specifies a custom DNS lookup function."

2020-11-05 20:41 UTC, jennyEckstein commented on lib/config-base.d.ts
> +import { LookupFunction } from 'net';
Generally its better to put requires for build-in modules before external and local imports

2020-11-05 20:45 UTC, vrMars commented on dist/aws-sdk-react-native.js
> + 			 *       lookups or instead use a cache to resolve on each lookup attempt.
looks okay in the raw, might just be the web formatting on github.

2020-11-05 21:10 UTC, BizzlePop34 approved these changes

2020-11-09 18:04 UTC, eaviles approved these changes

2020-11-09 18:05 UTC, jennyEckstein approved these changes

2020-11-09 18:05 UTC, merged